import { ArrowLeft, ChevronRight, Clock3, FlaskConical, ListRestart, Search } from 'lucide-react'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import { EmptyState } from '@/shared/components/EmptyState'
import { LoadingState } from '@/shared/components/LoadingState'
import { Toast } from '@/shared/components/Toast'
import { ObservabilityActiveFilters, datePresetRange, localDateTimeInput, type ObservabilityDatePreset } from '@/features/observability/components/ObservabilityFilters'
import { ObservabilityFlow, ObservabilityPagination, ObservabilityStatusBadge, formatObservabilityTimestamp } from '@/features/observability/components/ObservabilityPresentation'
import { getWebhook, listWebhookDeliveries, type WebhookDelivery, type WebhookRecord } from '../api/webhooksApi'

const pageSize = 25
const toTimestamp = (value: string) => value ? new Date(value).getTime() : undefined
const inputFromTimestamp = (value: string | null) => { const date = value ? new Date(Number(value)) : null; return date && !Number.isNaN(date.getTime()) ? localDateTimeInput(date) : '' }

export function WebhookDeliveriesPage() {
  const navigate = useNavigate(); const location = useLocation(); const { webhookId } = useParams(); const initial = new URLSearchParams(location.search)
  const [webhook, setWebhook] = useState<WebhookRecord | null>(null); const [items, setItems] = useState<WebhookDelivery[]>([]); const [total, setTotal] = useState(0); const [offset, setOffset] = useState(Number(initial.get('offset') || 0)); const [status, setStatus] = useState(initial.get('status') || ''); const [operation, setOperation] = useState(initial.get('operation') || ''); const [eventType, setEventType] = useState(initial.get('event_type') || ''); const [testFilter, setTestFilter] = useState(initial.get('is_test') === 'true' ? 'test' : initial.get('is_test') === 'false' ? 'normal' : 'all'); const [deliveryId, setDeliveryId] = useState(initial.get('delivery_id') || ''); const [eventId, setEventId] = useState(initial.get('event_id') || ''); const [requestId, setRequestId] = useState(initial.get('request_id') || ''); const [correlationId, setCorrelationId] = useState(initial.get('correlation_id') || ''); const [dateFrom, setDateFrom] = useState(inputFromTimestamp(initial.get('date_from'))); const [dateTo, setDateTo] = useState(inputFromTimestamp(initial.get('date_to'))); const [preset, setPreset] = useState<ObservabilityDatePreset>(''); const [search, setSearch] = useState(initial.get('search') || ''); const [searchDraft, setSearchDraft] = useState(initial.get('search') || ''); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState<string | null>(null)
  const resetOffset = () => setOffset(0)
  const hasFilters = Boolean(status || operation || eventType || testFilter !== 'all' || deliveryId || eventId || requestId || correlationId || dateFrom || dateTo || search)
  const load = useCallback(async (nextOffset = offset) => { if (!webhookId) return; setError(null); setIsLoading(true); const from = toTimestamp(dateFrom); const to = toTimestamp(dateTo); if (from !== undefined && to !== undefined && from > to) { setError('La fecha Desde debe ser anterior o igual a Hasta.'); setIsLoading(false); return } try { const [item, deliveries] = await Promise.all([getWebhook(webhookId), listWebhookDeliveries(webhookId, { limit: pageSize, offset: nextOffset, status: status || undefined, operation: operation || undefined, eventType: eventType || undefined, isTest: testFilter === 'test' ? true : testFilter === 'normal' ? false : undefined, deliveryId: deliveryId.trim() || undefined, eventId: eventId.trim() || undefined, requestId: requestId.trim() || undefined, correlationId: correlationId.trim() || undefined, search: search || undefined, dateFrom: from, dateTo: to })]); setWebhook(item); setItems(deliveries.items); setTotal(deliveries.total); setOffset(deliveries.offset) } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudieron cargar las entregas.') } finally { setIsLoading(false) } }, [correlationId, dateFrom, dateTo, deliveryId, eventId, eventType, offset, operation, requestId, search, status, testFilter, webhookId])
  useEffect(() => { void load(offset) }, [webhookId, status, operation, eventType, testFilter, deliveryId, eventId, requestId, correlationId, dateFrom, dateTo, search])
  useEffect(() => { const params = new URLSearchParams(); const values: Record<string, string | undefined> = { status: status || undefined, operation: operation || undefined, event_type: eventType || undefined, is_test: testFilter === 'all' ? undefined : String(testFilter === 'test'), delivery_id: deliveryId || undefined, event_id: eventId || undefined, request_id: requestId || undefined, correlation_id: correlationId || undefined, search: search || undefined, date_from: toTimestamp(dateFrom)?.toString(), date_to: toTimestamp(dateTo)?.toString(), offset: offset ? String(offset) : undefined }; Object.entries(values).forEach(([key, value]) => { if (value) params.set(key, value) }); const next = params.toString(); if (next !== location.search.slice(1)) navigate({ pathname: location.pathname, search: next ? `?${next}` : '' }, { replace: true }) }, [correlationId, dateFrom, dateTo, deliveryId, eventId, eventType, location.pathname, location.search, navigate, offset, operation, requestId, search, status, testFilter])
  const clearFilters = () => { setStatus(''); setOperation(''); setEventType(''); setTestFilter('all'); setDeliveryId(''); setEventId(''); setRequestId(''); setCorrelationId(''); setDateFrom(''); setDateTo(''); setPreset(''); setSearch(''); setSearchDraft(''); resetOffset() }
  const applyPreset = (next: ObservabilityDatePreset) => { setPreset(next); const range = datePresetRange(next); setDateFrom(range.from); setDateTo(range.to); resetOffset() }
  const submitSearch = (event: FormEvent) => { event.preventDefault(); setSearch(searchDraft.trim()); resetOffset() }
  if (isLoading && !webhook) return <LoadingState label="Cargando entregas…" />
  const activeFilters = [{ label: 'Estado', value: status }, { label: 'Operación', value: operation }, { label: 'Evento', value: eventType }, { label: 'Tipo', value: testFilter === 'all' ? '' : testFilter }, { label: 'Delivery ID', value: deliveryId }, { label: 'Event ID', value: eventId }, { label: 'Request ID', value: requestId }, { label: 'Correlation ID', value: correlationId }, { label: 'Búsqueda', value: search }, { label: 'Fecha', value: preset || (dateFrom || dateTo ? 'Personalizado' : '') }].filter((filter) => Boolean(filter.value))
  return <section className="webhooks-page"><button type="button" className="client-back-link" onClick={() => navigate(webhookId ? `/webhooks/${webhookId}` : '/webhooks')}><ArrowLeft size={16} /> {webhook?.name || 'Webhook'}</button><div className="webhooks-heading webhook-deliveries-heading"><div><p>Entregas</p><h2>{webhook?.name || 'Historial de entregas'}</h2><span>{total} resultado{total === 1 ? '' : 's'} · más reciente primero.</span></div><button type="button" className="client-button-secondary" onClick={() => void load()} disabled={isLoading}><ListRestart size={15} /> Actualizar</button></div><Toast message={error} tone="error" onDismiss={() => setError(null)} />
    <form className="observability-search" onSubmit={submitSearch}><Search size={17} aria-hidden="true" /><input value={searchDraft} onChange={(event) => setSearchDraft(event.target.value)} maxLength={256} placeholder="Buscar delivery, event, request o correlation…" aria-label="Buscar por identificador" /><button type="submit" className="client-button-secondary">Buscar</button></form>
    <div className="webhook-delivery-filters"><label>Estado<select value={status} onChange={(event) => { setStatus(event.target.value); resetOffset() }}><option value="">Todos</option><option value="success">Exitosas</option><option value="failed">Fallidas</option><option value="timeout">Timeout</option><option value="network_error">Error de red</option><option value="configuration_error">Configuración</option></select></label><label>Operación<select value={operation} onChange={(event) => { setOperation(event.target.value); resetOffset() }}><option value="">Todas</option><option value="webhook.delivery">webhook.delivery</option><option value="webhook.test">webhook.test</option></select></label><label>Evento<input value={eventType} onChange={(event) => { setEventType(event.target.value); resetOffset() }} placeholder="event_type" /></label><label>Tipo<select value={testFilter} onChange={(event) => { setTestFilter(event.target.value); resetOffset() }}><option value="all">Normales y pruebas</option><option value="normal">Sólo normales</option><option value="test">Sólo pruebas</option></select></label><label>Rango<select value={preset} onChange={(event) => applyPreset(event.target.value as ObservabilityDatePreset)}><option value="">Personalizado</option><option value="today">Hoy</option><option value="24h">Últimas 24 horas</option><option value="7d">Últimos 7 días</option><option value="30d">Últimos 30 días</option></select></label><label>Desde<input type="datetime-local" value={dateFrom} onChange={(event) => { setPreset(''); setDateFrom(event.target.value); resetOffset() }} /></label><label>Hasta<input type="datetime-local" value={dateTo} onChange={(event) => { setPreset(''); setDateTo(event.target.value); resetOffset() }} /></label><label>Correlation ID<input value={correlationId} onChange={(event) => { setCorrelationId(event.target.value); resetOffset() }} placeholder="correlation_id" /></label><label>Request ID<input value={requestId} onChange={(event) => { setRequestId(event.target.value); resetOffset() }} placeholder="request_id" /></label><label>Event ID<input value={eventId} onChange={(event) => { setEventId(event.target.value); resetOffset() }} placeholder="event_id" /></label><label>Delivery ID<input value={deliveryId} onChange={(event) => { setDeliveryId(event.target.value); resetOffset() }} placeholder="delivery_id" /></label></div><p className="observability-timezone">Las fechas se muestran en tu zona horaria local y se consultan en UTC.</p><ObservabilityActiveFilters filters={activeFilters} onClear={clearFilters} />
    {!isLoading && !error && items.length === 0 ? <EmptyState icon={Clock3} title={hasFilters ? 'No encontramos resultados con estos filtros.' : 'No hay deliveries para este webhook.'} description={hasFilters ? 'Probá ajustar o limpiar los filtros.' : 'Las pruebas y los eventos enviados aparecerán aquí.'} /> : null}
    {!error && items.length > 0 ? <ol className="webhook-center-deliveries">{items.map((delivery) => <li key={delivery.id}><ObservabilityStatusBadge status={delivery.semanticStatus} /><div><strong>{delivery.isTest ? <><FlaskConical size={14} /> {delivery.operation}</> : delivery.eventType || delivery.operation}</strong><span>{formatObservabilityTimestamp(delivery.timestamp)}{delivery.correlationId ? ` · Correlation ${delivery.correlationId}` : ''}</span><ObservabilityFlow source="Gateway" destination="Bot" durationMs={delivery.durationMs} responseStatus={delivery.statusCode || null} /></div><div className="delivery-meta"><span>{delivery.statusCode ? `HTTP ${delivery.statusCode}` : 'Sin HTTP'}</span><span>{Math.round(delivery.durationMs)} ms</span><span>{delivery.attemptCount} intento{delivery.attemptCount === 1 ? '' : 's'}</span></div><button type="button" className="icon-button" aria-label="Ver detalle de entrega" onClick={() => navigate(`/webhooks/${webhookId}/deliveries/${delivery.id}`)}><ChevronRight size={18} /></button></li>)}</ol> : null}
    <ObservabilityPagination total={total} limit={pageSize} offset={offset} loading={isLoading} onPrevious={() => void load(Math.max(0, offset - pageSize))} onNext={() => void load(offset + pageSize)} />
  </section>
}
