import { Activity, ArrowLeft, CheckCircle2, CircleAlert, FlaskConical, Network, Pencil, Power, Trash2, Webhook } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import type { Connection } from '@/domain/connection'
import { ConfirmDialog } from '@/shared/components/ConfirmDialog'
import { EmptyState } from '@/shared/components/EmptyState'
import { LoadingState } from '@/shared/components/LoadingState'
import { Toast } from '@/shared/components/Toast'
import { listConnections } from '@/features/connections/api/connectionsApi'
import { deleteWebhook, diagnoseWebhook, getWebhook, listWebhookDeliveries, setWebhookEnabled, testWebhook, updateWebhook, type WebhookDiagnosis, type WebhookRecord, type WebhookTestResult } from '../api/webhooksApi'
import { SafeJsonViewer } from '../components/SafeJsonViewer'
import { WebhookForm } from '../components/WebhookForm'

function dateTime(value: string | null): string { return value ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'No disponible' }
function eventLabel(filters: Record<string, boolean>): string { const labels = { business: 'Negocio', transport: 'Transporte', operational: 'Operativo' }; return Object.entries(filters).filter(([, value]) => value).map(([key]) => labels[key as keyof typeof labels] || key).join(' · ') || 'Sin eventos' }
function authLabel(webhook: WebhookRecord): string { return webhook.authType === 'NONE' ? 'Sin autenticación' : `${webhook.authType} · configurada` }

export function WebhookDetailPage() {
  const navigate = useNavigate(); const { webhookId } = useParams()
  const [webhook, setWebhook] = useState<WebhookRecord | null>(null); const [connections, setConnections] = useState<Connection[]>([])
  const [deliveriesCount, setDeliveriesCount] = useState<number | null>(null); const [isLoading, setIsLoading] = useState(true); const [isEditing, setIsEditing] = useState(false)
  const [running, setRunning] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null)
  const [isTestConfirmOpen, setIsTestConfirmOpen] = useState(false); const [isDeleteConfirmOpen, setIsDeleteConfirmOpen] = useState(false); const [testResult, setTestResult] = useState<WebhookTestResult | null>(null); const [diagnosis, setDiagnosis] = useState<WebhookDiagnosis | null>(null); const [configurationReview, setConfigurationReview] = useState<string | null>(null)
  const load = useCallback(async () => { if (!webhookId) return; setError(null); setIsLoading(true); try { const [item, availableConnections, deliveries] = await Promise.all([getWebhook(webhookId), listConnections(), listWebhookDeliveries(webhookId)]); setWebhook(item); setConnections(availableConnections); setDeliveriesCount(deliveries.total) } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo cargar el webhook.') } finally { setIsLoading(false) } }, [webhookId])
  useEffect(() => { void load() }, [load])
  const connection = connections.find((item) => item.id === webhook?.connectionId)

  async function save(input: Parameters<typeof updateWebhook>[1]) { if (!webhook) return; setRunning('save'); setError(null); try { setWebhook(await updateWebhook(webhook.id, input)); setIsEditing(false); setNotice('Webhook actualizado.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar el webhook.') } finally { setRunning(null) } }
  async function toggle() { if (!webhook) return; setRunning('toggle'); setError(null); try { setWebhook(await setWebhookEnabled(webhook.id, !webhook.enabled)); setNotice(webhook.enabled ? 'Webhook desactivado.' : 'Webhook activado.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo cambiar el estado del webhook.') } finally { setRunning(null) } }
  async function runTest() { if (!webhook) return; setRunning('test'); setError(null); try { const result = await testWebhook(webhook.id); setTestResult(result); setNotice(result.ok ? 'Prueba enviada correctamente.' : 'La prueba terminó con un error.'); await load() } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo ejecutar la prueba.') } finally { setRunning(null); setIsTestConfirmOpen(false) } }
  async function diagnose() { if (!webhook) return; setRunning('diagnose'); setError(null); try { setDiagnosis(await diagnoseWebhook(webhook.id)) } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo ejecutar el diagnóstico.') } finally { setRunning(null) } }
  async function remove() { if (!webhook) return; setRunning('delete'); setError(null); try { await deleteWebhook(webhook.id); navigate('/webhooks') } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo eliminar el webhook.') } finally { setRunning(null); setIsDeleteConfirmOpen(false) } }
  function verifyConfiguration() { if (!webhook) return; setConfigurationReview(!webhook.url ? 'Falta una URL de destino.' : !webhook.enabled ? 'La configuración es válida, pero el webhook está desactivado.' : !Object.values(webhook.eventFilters).some(Boolean) ? 'Seleccioná al menos un tipo de evento.' : `Configuración lista: ${eventLabel(webhook.eventFilters)} · ${authLabel(webhook)}.`) }

  if (isLoading) return <LoadingState label="Cargando webhook…" />
  if (!webhook) return <section className="webhooks-page"><button type="button" className="client-back-link" onClick={() => navigate('/webhooks')}><ArrowLeft size={16} /> Webhooks</button><EmptyState icon={Webhook} title="Webhook no disponible." description={error || 'No se pudo encontrar este webhook.'} /></section>
  return <section className="webhook-detail"><button type="button" className="client-back-link" onClick={() => navigate('/webhooks')}><ArrowLeft size={16} /> Webhooks</button><div className="webhook-detail-heading"><div><span className={webhook.enabled ? 'webhook-enabled is-active' : 'webhook-enabled'}>{webhook.enabled ? '● Activo' : '○ Desactivado'}</span><h2>{webhook.name}</h2><p>{connection?.name || 'Conexión no disponible'} · actualizado {dateTime(webhook.updatedAt)}</p></div><div className="client-detail-actions"><button type="button" className="client-button-secondary" onClick={() => setIsEditing(true)}><Pencil size={15} /> Editar</button><button type="button" className="client-button-secondary" disabled={running === 'toggle'} onClick={() => void toggle()}><Power size={15} /> {running === 'toggle' ? 'Actualizando…' : webhook.enabled ? 'Desactivar' : 'Activar'}</button></div></div><Toast message={error} tone="error" onDismiss={() => setError(null)} /><Toast message={notice} onDismiss={() => setNotice(null)} />
    {isEditing ? <WebhookForm webhook={webhook} connections={connections} isSubmitting={running === 'save'} onCancel={() => setIsEditing(false)} onSubmit={save} /> : null}
    <div className="webhook-detail-grid"><section className="webhook-detail-section"><h3>Información</h3><dl><div><dt>Conexión</dt><dd>{connection?.name || webhook.connectionId}</dd></div><div><dt>Creado</dt><dd>{dateTime(webhook.createdAt)}</dd></div><div><dt>Actualizado</dt><dd>{dateTime(webhook.updatedAt)}</dd></div></dl></section><section className="webhook-detail-section"><h3>Configuración</h3><dl><div><dt>URL</dt><dd><code>{webhook.url}</code></dd></div><div><dt>Autenticación</dt><dd>{authLabel(webhook)}</dd></div></dl></section><section className="webhook-detail-section"><h3>Eventos y filtros</h3><p>{eventLabel(webhook.eventFilters)}</p><button type="button" className="operation-link" onClick={verifyConfiguration}>Verificar configuración</button>{configurationReview ? <p className="webhook-inline-result">{configurationReview}</p> : null}</section><section className="webhook-detail-section"><h3>Actividad</h3><dl><div><dt>Última entrega</dt><dd>{dateTime(webhook.lastUsedAt)}</dd></div><div><dt>Último resultado</dt><dd>{webhook.lastStatusCode ? `HTTP ${webhook.lastStatusCode}` : webhook.lastStatus || 'Sin actividad'}</dd></div><div><dt>Última respuesta</dt><dd>{webhook.lastLatencyMs !== null ? `${Math.round(webhook.lastLatencyMs)} ms` : 'Sin respuesta'}</dd></div></dl></section></div>
    <section className="webhook-actions"><div><h3>Acciones</h3><p>Verificar configuración no realiza una solicitud. La prueba sí se envía al destino configurado.</p></div><div><button type="button" className="client-button-primary" disabled={running === 'test' || !webhook.enabled} onClick={() => setIsTestConfirmOpen(true)}><FlaskConical size={15} /> Probar webhook</button><button type="button" className="client-button-secondary" disabled={running === 'diagnose'} onClick={() => void diagnose()}><Network size={15} /> {running === 'diagnose' ? 'Diagnosticando…' : 'Diagnosticar'}</button><button type="button" className="client-button-danger" disabled={running === 'delete'} onClick={() => setIsDeleteConfirmOpen(true)}><Trash2 size={15} /> Eliminar</button></div></section>
    {testResult ? <div className={`webhook-operation-result ${testResult.ok ? 'is-success' : 'is-error'}`}>{testResult.ok ? <CheckCircle2 size={19} /> : <CircleAlert size={19} />}<div><strong>{testResult.ok ? 'Entrega exitosa' : 'La entrega falló'}</strong><span>{testResult.status ? `HTTP ${testResult.status}` : 'Sin respuesta HTTP'}{testResult.latencyMs !== null ? ` · ${Math.round(testResult.latencyMs)} ms` : ''}{testResult.error ? ` · ${testResult.error}` : ''}</span></div></div> : null}
    {diagnosis ? <section className="webhook-diagnosis"><h3>Diagnóstico de conectividad</h3><p>DNS, conexión TCP y HTTP. No valida la configuración funcional del webhook.</p><SafeJsonViewer value={diagnosis} /></section> : null}
    <section className="webhook-deliveries-preview"><div><h3>Entregas</h3><p>{deliveriesCount ? `${deliveriesCount} entrega${deliveriesCount === 1 ? '' : 's'} recientes.` : 'Este webhook todavía no tiene entregas.'}</p></div><button type="button" className="client-button-secondary" onClick={() => navigate(`/webhooks/${webhook.id}/deliveries`)}>Ver todas <Activity size={15} /></button></section>
    <ConfirmDialog isOpen={isTestConfirmOpen} title="Enviar prueba de webhook" description="Se enviará una solicitud de prueba al endpoint configurado." confirmLabel="Enviar prueba" submittingLabel="Enviando prueba…" tone="default" isSubmitting={running === 'test'} onCancel={() => setIsTestConfirmOpen(false)} onConfirm={() => void runTest()} /><ConfirmDialog isOpen={isDeleteConfirmOpen} title="¿Eliminar este webhook?" description="Dejará de recibir nuevas entregas y se eliminará su configuración. El historial existente se conserva según la retención configurada." confirmLabel="Eliminar webhook" submittingLabel="Eliminando…" isSubmitting={running === 'delete'} onCancel={() => setIsDeleteConfirmOpen(false)} onConfirm={() => void remove()} />
  </section>
}
