import { useEffect, useMemo, useRef, useState } from 'react'
import useSWR from 'swr'
import { AlertTriangle, ArrowLeft, BadgeCheck, Check, CheckCircle2, ChevronRight, CircleDot, ClipboardList, ExternalLink, FlaskConical, Loader2, LogIn, Play, RefreshCw, ShieldCheck, Sparkles, X } from 'lucide-react'
import { api } from '../lib/api'
import { publicChannels, resolveFeatures } from '../lib/features'
import type { ChannelCatalogItem, ChannelMethod, ConnectionType, CreateConnectionPayload, Instance, MetaSignupConfig } from '../types'
import type { CreateModalProps } from './CreateModal'

type Phase = 'info' | 'provider' | 'validation' | 'embedded' | 'provisioning' | 'verification' | 'smoke' | 'complete' | 'failed' | 'cancelled'
type HistoryEntry = { id: string; startedAt: number; endedAt?: number; name: string; company: string; operator: string; provider: string; result: 'completed' | 'failed' | 'cancelled'; durationMs?: number }
type Draft = { name: string; company: string; operator: string; channelId?: string; methodId?: string; phase: Phase; startedAt: number; updatedAt: number; provider?: string; instanceName?: string; manualMode?: boolean }

const DRAFT_KEY = 'botly.onboarding.wizard.v2'
const HISTORY_KEY = 'botly.onboarding.history.v1'
const NAME_PATTERN = /^[a-z0-9_]{1,64}$/
const phases: Array<{ id: Exclude<Phase, 'failed' | 'cancelled'>; label: string; detail: string }> = [
  { id: 'info', label: 'Información', detail: 'Identidad de la conexión' },
  { id: 'provider', label: 'Proveedor', detail: 'Canal y método' },
  { id: 'validation', label: 'Validaciones', detail: 'Requisitos previos' },
  { id: 'embedded', label: 'Embedded Signup', detail: 'Autenticación de Meta' },
  { id: 'provisioning', label: 'Provisioning', detail: 'Recursos y credenciales' },
  { id: 'verification', label: 'Verificación', detail: 'Estado operativo' },
  { id: 'smoke', label: 'Smoke Test', detail: 'Comprobación final' },
  { id: 'complete', label: 'Finalización', detail: 'Accesos operativos' },
]

declare global {
  interface Window {
    FB?: { init: (options: Record<string, unknown>) => void; login: (callback: (response: { authResponse?: { code?: string }; status?: string }) => void, options: Record<string, unknown>) => void }
    fbAsyncInit?: () => void
  }
}

function readDraft(): Draft | null { try { const value = JSON.parse(localStorage.getItem(DRAFT_KEY) || 'null'); return value && typeof value === 'object' && value.name ? value as Draft : null } catch { return null } }
function saveDraft(draft: Draft) { localStorage.setItem(DRAFT_KEY, JSON.stringify(draft)) }
function clearDraft() { localStorage.removeItem(DRAFT_KEY) }
function readHistory(): HistoryEntry[] { try { const value = JSON.parse(localStorage.getItem(HISTORY_KEY) || '[]'); return Array.isArray(value) ? value : [] } catch { return [] } }
function writeHistory(entry: HistoryEntry) { const history = [entry, ...readHistory().filter(item => item.id !== entry.id)].slice(0, 30); localStorage.setItem(HISTORY_KEY, JSON.stringify(history)) }
function isFacebookOrigin(origin: string) { try { const url = new URL(origin); return url.protocol === 'https:' && (url.hostname === 'facebook.com' || url.hostname.endsWith('.facebook.com')) } catch { return false } }
function parseSession(event: MessageEvent): { phoneNumberId: string; businessAccountId: string; raw: Record<string, unknown> } | 'cancelled' | null { if (!isFacebookOrigin(String(event.origin || ''))) return null; let payload: unknown = event.data; if (typeof payload === 'string') { try { payload = JSON.parse(payload) } catch { return null } }; if (!payload || typeof payload !== 'object') return null; const data = payload as Record<string, unknown>; if (data.type !== 'WA_EMBEDDED_SIGNUP') return null; const eventName = String(data.event || '').toUpperCase(); if (['CANCEL', 'CANCELLED', 'ERROR'].includes(eventName)) return 'cancelled'; if (!['FINISH', 'FINISH_WHATSAPP_BUSINESS_APP_ONBOARDING'].includes(eventName)) return null; const result = data.data && typeof data.data === 'object' ? data.data as Record<string, unknown> : data; const phoneNumberId = String(result.phone_number_id || result.phoneNumberId || ''); const businessAccountId = String(result.waba_id || result.business_account_id || result.businessAccountId || ''); return phoneNumberId && businessAccountId ? { phoneNumberId, businessAccountId, raw: data } : null }
function waitForSession() { return new Promise<{ phoneNumberId: string; businessAccountId: string; raw: Record<string, unknown> }>((resolve, reject) => { const timeout = window.setTimeout(() => { window.removeEventListener('message', listener); reject(new Error('Embedded Signup excedió el tiempo de espera. Puedes continuarlo cuando estés listo.')) }, 120000); const listener = (event: MessageEvent) => { const session = parseSession(event); if (!session) return; window.clearTimeout(timeout); window.removeEventListener('message', listener); session === 'cancelled' ? reject(new Error('Embedded Signup fue cancelado.')) : resolve(session) }; window.addEventListener('message', listener) }) }
async function loadFacebook(appId: string, graphVersion: string) { if (window.FB) { window.FB.init({ appId, autoLogAppEvents: true, xfbml: true, version: graphVersion }); return }; await new Promise<void>((resolve, reject) => { const timeout = window.setTimeout(() => reject(new Error('La carga de Embedded Signup tardó demasiado.')), 20000); window.fbAsyncInit = () => { window.FB?.init({ appId, autoLogAppEvents: true, xfbml: true, version: graphVersion }); window.clearTimeout(timeout); resolve() }; const existing = document.getElementById('facebook-jssdk'); if (existing) { const poll = window.setInterval(() => { if (!window.FB) return; window.clearInterval(poll); window.clearTimeout(timeout); window.FB.init({ appId, autoLogAppEvents: true, xfbml: true, version: graphVersion }); resolve() }, 150); return }; const script = document.createElement('script'); script.id = 'facebook-jssdk'; script.src = 'https://connect.facebook.net/en_US/sdk.js'; script.async = true; script.defer = true; script.onerror = () => reject(new Error('No se pudo cargar Embedded Signup.')); document.body.appendChild(script) }) }
function facebookLogin(configId: string) { return new Promise<string>((resolve, reject) => { if (!window.FB) { reject(new Error('Embedded Signup no está disponible.')); return }; window.FB.login(response => { const code = response.authResponse?.code; code ? resolve(code) : reject(new Error(response.status === 'not_authorized' ? 'No autorizaste la conexión.' : 'No se completó el inicio de sesión.')) }, { config_id: configId, response_type: 'code', override_default_response_type: true, extras: { sessionInfoVersion: '3', featureType: 'whatsapp_business_app_onboarding' } }) }) }
function phaseIndex(phase: Phase) { const index = phases.findIndex(item => item.id === phase); return index < 0 ? 0 : index }
function duration(ms: number) { return ms < 60000 ? `${Math.max(1, Math.round(ms / 1000))} s` : `${Math.floor(ms / 60000)} min` }
function stepStatus(phase: Phase, id: Exclude<Phase, 'failed' | 'cancelled'>) { if (phase === 'failed' || phase === 'cancelled') return id === 'complete' ? 'pending' : 'done'; const current = phaseIndex(phase); const index = phaseIndex(id); return index < current ? 'done' : index === current ? 'current' : 'pending' }

export default function ConnectionOnboardingWizard({ config, onClose, onCreate, onOpenWorkspace, onOpenTests }: CreateModalProps) {
  const initial = useRef(readDraft()).current
  const [name, setName] = useState(initial?.name || '')
  const [company, setCompany] = useState(initial?.company || '')
  const [operator, setOperator] = useState(initial?.operator || localStorage.getItem('botly.test-center.operator.v1') || 'Operador local')
  const [phase, setPhase] = useState<Phase>(initial?.phase && !['complete', 'cancelled'].includes(initial.phase) ? initial.phase : 'info')
  const [startedAt] = useState(initial?.startedAt || Date.now())
  const [channels, setChannels] = useState<ChannelCatalogItem[]>([])
  const [selected, setSelected] = useState<{ channel: ChannelCatalogItem; method: ChannelMethod } | null>(null)
  const [manualMode, setManualMode] = useState(Boolean(initial?.manualMode))
  const [credentials, setCredentials] = useState({ accessToken: '', phoneNumberId: '', businessId: '' })
  const [created, setCreated] = useState<Instance | null>(initial?.instanceName ? { id: initial.instanceName, name: initial.instanceName, status: 'connecting' } : null)
  const [error, setError] = useState<{ message: string; action: string; technical?: string } | null>(null)
  const [loading, setLoading] = useState(false)
  const [showTechnical, setShowTechnical] = useState(false)
  const [resumeNotice, setResumeNotice] = useState(Boolean(initial))

  const { data: catalog, isLoading: catalogLoading } = useSWR(config.apiKey ? ['wizard-catalog', config.url] : null, () => api.channels.list(config), { revalidateOnFocus: false })
  const connectionType = (selected?.method.currentConnectionType || 'baileys') as ConnectionType
  const provider = selected?.method.displayName || initial?.provider || 'Meta'
  const { data: onboarding, mutate: refreshOnboarding } = useSWR(
    created && connectionType === 'cloud' ? ['wizard-onboarding', created.name] : null,
    () => api.metaSignup.status(config, created!.name),
    { refreshInterval: phase === 'provisioning' ? 3500 : 0, shouldRetryOnError: false }
  )
  const methods = useMemo(() => publicChannels(catalog || channels, resolveFeatures(undefined)).flatMap(channel => channel.methods.map(method => ({ channel, method }))).filter(item => item.method.visible && item.method.enabled && item.method.currentConnectionType).sort((a, b) => a.channel.sortOrder - b.channel.sortOrder || a.method.sortOrder - b.method.sortOrder), [catalog, channels])

  useEffect(() => { if (catalog) setChannels(catalog.filter(channel => channel.visible && channel.enabled)) }, [catalog])
  useEffect(() => { if (!initial || selected || !methods.length) return; const restored = methods.find(item => item.channel.id === initial.channelId && item.method.id === initial.methodId); if (restored) setSelected(restored) }, [initial, methods, selected])
  useEffect(() => { if (!name) return; saveDraft({ name, company, operator, channelId: selected?.channel.id, methodId: selected?.method.id, phase, startedAt, updatedAt: Date.now(), provider, instanceName: created?.name || initial?.instanceName || (phase === 'provisioning' || phase === 'verification' ? name : undefined), manualMode }); localStorage.setItem('botly.test-center.operator.v1', operator) }, [name, company, operator, selected, phase, startedAt, provider, created, initial, manualMode])
  useEffect(() => { if (onboarding?.status === 'READY' && phase === 'provisioning') { setPhase('verification'); setError(null) } }, [onboarding, phase])

  const fail = (message: string, action: string, technical?: string) => { setError({ message, action, technical }); setPhase('failed'); setLoading(false); writeHistory({ id: `${startedAt}-${name}`, name, company, operator, provider, startedAt, endedAt: Date.now(), durationMs: Date.now() - startedAt, result: 'failed' }) }
  const validateInfo = () => { if (!name.trim()) return 'Indica un nombre para la conexión.'; if (!NAME_PATTERN.test(name.trim())) return 'Usa solo minúsculas, números y guion bajo (máximo 64 caracteres).'; return '' }
  const selectProvider = (item: { channel: ChannelCatalogItem; method: ChannelMethod }) => { setSelected(item); setError(null); setPhase('validation') }
  const runPrechecks = async () => { if (!selected) { setPhase('provider'); return }; const invalid = validateInfo(); if (invalid) { setError({ message: invalid, action: 'Corrige la información de la conexión para continuar.' }); setPhase('info'); return }; setLoading(true); setError(null); try { if (connectionType === 'cloud' && !manualMode) { const signupConfig: MetaSignupConfig = await api.metaSignup.config(config); if (!signupConfig.enabled || !signupConfig.app_id || !signupConfig.config_id) throw new Error('Meta Embedded Signup no está configurado en este Gateway.'); setPhase('embedded') } else { await startManual() } } catch (cause) { fail('No se pudieron completar las validaciones previas.', 'Revisa la configuración del proveedor o usa el modo administrador si corresponde.', cause instanceof Error ? cause.message : String(cause)) } finally { setLoading(false) } }
  const create = async (payload: CreateConnectionPayload) => { setPhase('provisioning'); setLoading(true); try { const instance = await onCreate(payload); setCreated(instance); if (payload.connectionType === 'cloud_embedded') { await refreshOnboarding(); setPhase('verification') } else setPhase('verification') } catch (cause) { fail('El provisioning no pudo finalizar.', 'Revisa la etapa indicada y vuelve a intentar desde este asistente.', cause instanceof Error ? cause.message : String(cause)) } finally { setLoading(false) } }
  const startEmbedded = async () => { const invalid = validateInfo(); if (invalid) { setError({ message: invalid, action: 'Corrige el nombre de la conexión.' }); return }; setLoading(true); setError(null); try { const signupConfig = await api.metaSignup.config(config); if (!signupConfig.enabled || !signupConfig.app_id || !signupConfig.config_id) throw new Error('Meta Embedded Signup no está configurado en este Gateway.'); await loadFacebook(signupConfig.app_id, signupConfig.graph_version); const sessionPromise = waitForSession(); const code = await facebookLogin(signupConfig.config_id); const session = await sessionPromise; await create({ connectionType: 'cloud_embedded', instanceName: name.trim(), code, phoneNumberId: session.phoneNumberId, businessAccountId: session.businessAccountId, sessionInfo: session.raw, coexistenceRequested: signupConfig.supports_coexistence }) } catch (cause) { fail('Embedded Signup no se completó.', 'Puedes retomar esta etapa e iniciar sesión nuevamente cuando estés listo.', cause instanceof Error ? cause.message : String(cause)) } }
  const startManual = async () => { const invalid = validateInfo(); if (invalid) { setError({ message: invalid, action: 'Corrige la información de la conexión.' }); return }; if (connectionType === 'cloud' && (!credentials.accessToken.trim() || !credentials.phoneNumberId.trim() || !credentials.businessId.trim())) { setError({ message: 'Faltan credenciales obligatorias.', action: 'Completa credencial, Phone Number ID y Business ID.' }); return }; await create(connectionType === 'cloud' ? { connectionType: 'cloud', instanceName: name.trim(), accessToken: credentials.accessToken.trim(), phoneNumberId: credentials.phoneNumberId.trim(), businessId: credentials.businessId.trim() } : { connectionType: 'baileys', instanceName: name.trim() }) }
  const complete = () => { const instanceName = created?.name || name; writeHistory({ id: `${startedAt}-${name}`, name: instanceName, company, operator, provider, startedAt, endedAt: Date.now(), durationMs: Date.now() - startedAt, result: 'completed' }); clearDraft(); setPhase('complete') }
  const cancel = () => { if (name) { saveDraft({ name, company, operator, channelId: selected?.channel.id, methodId: selected?.method.id, phase: 'cancelled', startedAt, updatedAt: Date.now(), provider, manualMode }); writeHistory({ id: `${startedAt}-${name}`, name, company, operator, provider, startedAt, endedAt: Date.now(), durationMs: Date.now() - startedAt, result: 'cancelled' }) }; onClose() }
  const retry = () => { setError(null); setPhase(created ? 'verification' : connectionType === 'cloud' && !manualMode ? 'embedded' : 'validation') }
  const details = onboarding?.details || {}
  const diagnostics = [
    ['OAuth', onboarding?.steps.oauth], ['Discovery / WABA', onboarding?.steps.discovery], ['Subscription', onboarding?.steps.subscription], ['Phone Number', onboarding?.steps.phone], ['Webhook', onboarding?.steps.webhook], ['Evolution', onboarding?.steps.evolution], ['Credenciales', onboarding?.steps.credentials],
  ]

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3 backdrop-blur-sm animate-fade-in"><div className="flex max-h-[calc(100vh-1.5rem)] w-full max-w-5xl flex-col overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900 animate-slide-up"><header className="flex items-center justify-between border-b border-zinc-800 px-5 py-4"><div><p className="text-xs font-medium uppercase tracking-wider text-blue-400">Provisioning guiado</p><h2 className="mt-1 text-lg font-semibold text-zinc-100">Nueva conexión</h2><p className="mt-1 text-[11px] text-zinc-600">Proceso iniciado {duration(Date.now() - startedAt)} atrás · progreso guardado automáticamente</p></div><button onClick={cancel} className="rounded-md p-2 text-zinc-500 hover:bg-zinc-800 hover:text-zinc-200" title="Cerrar"><X size={17} /></button></header><div className="flex min-h-0 flex-1 flex-col lg:flex-row"><aside className="border-b border-zinc-800 p-3 lg:w-64 lg:shrink-0 lg:border-b-0 lg:border-r lg:overflow-y-auto"><div className="flex gap-1 overflow-x-auto lg:flex-col">{phases.map(item => { const status = stepStatus(phase, item.id); return <div key={item.id} className={`flex min-w-36 items-center gap-2 rounded-lg px-2.5 py-2 ${status === 'current' ? 'bg-blue-950/40 text-blue-200' : 'text-zinc-500'}`}><span className={`flex h-5 w-5 items-center justify-center rounded-full text-[10px] ${status === 'done' ? 'bg-emerald-500 text-zinc-950' : status === 'current' ? 'border-2 border-blue-400' : 'border border-zinc-700'}`}>{status === 'done' ? <Check size={12} strokeWidth={3} /> : phaseIndex(item.id) + 1}</span><span><p className="text-xs font-medium">{item.label}</p><p className="hidden text-[10px] text-zinc-600 lg:block">{status === 'done' ? 'Completado' : status === 'current' ? 'En curso' : 'Pendiente'} · {item.detail}</p></span></div> })}</div></aside><main className="min-h-0 flex-1 overflow-y-auto p-5"><div className="mx-auto max-w-2xl">{resumeNotice ? <div className="mb-4 flex items-start justify-between gap-3 rounded-lg border border-blue-900/70 bg-blue-950/20 p-3 text-xs text-blue-200"><p>Se restauró el progreso seguro de <strong>{initial?.name}</strong>. Las credenciales y códigos temporales no se guardan en el navegador; si la autenticación venció, solo tendrás que repetir Embedded Signup.</p><button onClick={() => setResumeNotice(false)}><X size={14} /></button></div> : null}
      {phase === 'info' ? <section><h3 className="text-xl font-semibold text-zinc-100">Información de la conexión</h3><p className="mt-1 text-sm text-zinc-500">Define la identidad operativa antes de elegir un proveedor.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs text-zinc-400 sm:col-span-2">Nombre de la conexión<input value={name} onChange={event => setName(event.target.value.toLowerCase().replace(/[^a-z0-9_]/g, ''))} placeholder="acme_support" className="mt-1.5 w-full rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2.5 font-mono text-sm text-zinc-100" /><span className="mt-1 block text-zinc-600">Solo minúsculas, números y guion bajo.</span></label><label className="text-xs text-zinc-400">Empresa <input value={company} onChange={event => setCompany(event.target.value)} placeholder="Opcional" className="mt-1.5 w-full rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2.5 text-sm text-zinc-100" /></label><label className="text-xs text-zinc-400">Operador <input value={operator} onChange={event => setOperator(event.target.value)} className="mt-1.5 w-full rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2.5 text-sm text-zinc-100" /></label></div><div className="mt-6 flex justify-end"><button onClick={() => { const invalid = validateInfo(); if (invalid) setError({ message: invalid, action: 'Corrige la información para continuar.' }); else { setError(null); setPhase('provider') } }} className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-blue-500">Continuar <ChevronRight size={15} /></button></div></section> : null}
      {phase === 'provider' ? <section><button onClick={() => setPhase('info')} className="inline-flex items-center gap-1 text-xs text-zinc-500 hover:text-zinc-300"><ArrowLeft size={13} />Información</button><h3 className="mt-4 text-xl font-semibold text-zinc-100">Selecciona proveedor y método</h3><p className="mt-1 text-sm text-zinc-500">La arquitectura del wizard admite nuevos proveedores sin cambiar sus etapas.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{catalogLoading ? <><div className="h-32 animate-pulse rounded-xl border border-zinc-800 bg-zinc-950/50" /><div className="h-32 animate-pulse rounded-xl border border-zinc-800 bg-zinc-950/50" /></> : methods.map(item => { const cloud = item.method.currentConnectionType === 'cloud'; return <button key={`${item.channel.id}:${item.method.id}`} onClick={() => selectProvider(item)} className={`rounded-xl border p-4 text-left transition-colors ${cloud ? 'border-emerald-900/70 hover:border-emerald-500' : 'border-blue-900/70 hover:border-blue-500'} bg-zinc-950/50`}><div className="flex items-center justify-between"><BadgeCheck size={18} className={cloud ? 'text-emerald-400' : 'text-blue-400'} /><span className="text-[10px] uppercase text-zinc-500">{item.channel.displayName}</span></div><p className="mt-4 text-sm font-semibold text-zinc-100">{item.method.displayName}</p><p className="mt-1 text-xs text-zinc-500">{item.method.description}</p></button> })}</div></section> : null}
      {phase === 'validation' ? <section><h3 className="text-xl font-semibold text-zinc-100">Validaciones previas</h3><p className="mt-1 text-sm text-zinc-500">Confirmamos que el método seleccionado puede iniciar el provisioning.</p><div className="mt-5 space-y-2"><div className="rounded-lg border border-zinc-800 bg-zinc-950/50 p-3 text-sm text-zinc-300"><CheckCircle2 size={15} className="mr-2 inline text-emerald-400" />Nombre válido: <span className="font-mono">{name}</span></div><div className="rounded-lg border border-zinc-800 bg-zinc-950/50 p-3 text-sm text-zinc-300"><CheckCircle2 size={15} className="mr-2 inline text-emerald-400" />Método: {selected?.method.displayName}</div>{connectionType === 'cloud' ? <div className="rounded-lg border border-zinc-800 bg-zinc-950/50 p-3 text-sm text-zinc-300"><ShieldCheck size={15} className="mr-2 inline text-emerald-400" />Se validará la configuración pública de Meta antes de abrir Embedded Signup.</div> : null}</div><div className="mt-6 flex justify-between"><button onClick={() => setPhase('provider')} className="text-sm text-zinc-400 hover:text-zinc-200">Cambiar proveedor</button><button onClick={runPrechecks} disabled={loading} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{loading ? <Loader2 size={15} className="animate-spin" /> : <Play size={15} />}Validar y continuar</button></div></section> : null}
      {phase === 'embedded' ? <section><h3 className="text-xl font-semibold text-zinc-100">Embedded Signup</h3><p className="mt-1 text-sm text-zinc-500">Meta abrirá una ventana segura para seleccionar la WABA y el número.</p><div className="mt-5 rounded-xl border border-blue-900/70 bg-blue-950/20 p-4"><p className="font-medium text-blue-100">Esperando autenticación</p><p className="mt-1 text-xs text-blue-200/70">No guardamos códigos temporales. Si cierras el navegador, el wizard conserva la etapa y podrás reiniciar solo esta autenticación.</p></div>{manualMode ? <div className="mt-4 grid gap-3"><label className="text-xs text-zinc-400">Credencial principal<input type="password" value={credentials.accessToken} onChange={event => setCredentials(current => ({ ...current, accessToken: event.target.value }))} className="mt-1.5 w-full rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2.5 text-sm" /></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-zinc-400">Phone Number ID<input value={credentials.phoneNumberId} onChange={event => setCredentials(current => ({ ...current, phoneNumberId: event.target.value }))} className="mt-1.5 w-full rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2.5 text-sm" /></label><label className="text-xs text-zinc-400">Business ID<input value={credentials.businessId} onChange={event => setCredentials(current => ({ ...current, businessId: event.target.value }))} className="mt-1.5 w-full rounded-lg border border-zinc-700 bg-zinc-800 px-3 py-2.5 text-sm" /></label></div></div> : null}<div className="mt-6 flex flex-wrap justify-between gap-2"><button onClick={() => setManualMode(value => !value)} className="text-sm text-zinc-400 hover:text-zinc-200">{manualMode ? 'Usar Embedded Signup' : 'Modo administrador'}</button><button onClick={manualMode ? startManual : startEmbedded} disabled={loading} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{loading ? <Loader2 size={15} className="animate-spin" /> : <LogIn size={15} />}{manualMode ? 'Provisionar con credenciales' : 'Iniciar Embedded Signup'}</button></div></section> : null}
      {phase === 'provisioning' || phase === 'verification' ? <section><h3 className="text-xl font-semibold text-zinc-100">{phase === 'provisioning' ? 'Provisioning en curso' : 'Verificación operativa'}</h3><p className="mt-1 text-sm text-zinc-500">Estado reportado por el Meta Onboarding Engine; no se duplican validaciones.</p><div className="mt-5 grid gap-2 sm:grid-cols-2">{diagnostics.map(([label, completed]) => <div key={String(label)} className="flex items-center gap-2 rounded-lg border border-zinc-800 bg-zinc-950/50 p-3">{completed ? <CheckCircle2 size={16} className="text-emerald-400" /> : phase === 'provisioning' ? <Loader2 size={16} className="animate-spin text-blue-400" /> : <CircleDot size={16} className="text-zinc-600" />}<div><p className="text-sm text-zinc-200">{String(label)}</p><p className="text-[11px] text-zinc-500">{completed ? 'Completado' : phase === 'provisioning' ? 'En espera' : 'No disponible'}</p></div></div>)}</div>{onboarding?.errors?.length ? <div className="mt-4 rounded-lg border border-red-900/70 bg-red-950/20 p-3 text-sm text-red-200"><p className="font-medium">{onboarding.errors[onboarding.errors.length - 1].message}</p><p className="mt-1 text-xs">{onboarding.errors[onboarding.errors.length - 1].action || 'Revisa la etapa y vuelve a intentar.'}</p></div> : null}<div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-950/50 p-3 text-xs text-zinc-500"><p>Estado general: <span className="text-zinc-200">{onboarding?.status || (created ? 'Creado; esperando confirmación' : 'Provisionando')}</span></p>{details.discovery && typeof details.discovery === 'object' ? <p className="mt-1">WABA y Phone Number detectados por Discovery.</p> : null}</div><div className="mt-6 flex justify-end gap-2">{phase === 'provisioning' ? <button onClick={() => void refreshOnboarding()} className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-700 px-3 py-2 text-xs text-zinc-200"><RefreshCw size={13} />Actualizar estado</button> : <button onClick={() => setPhase('smoke')} className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white">Continuar a Smoke Test <ChevronRight size={15} /></button>}</div></section> : null}
      {phase === 'smoke' ? <section><h3 className="text-xl font-semibold text-zinc-100">Smoke Test</h3><p className="mt-1 text-sm text-zinc-500">La conexión está lista para una prueba operacional inmediata.</p><div className="mt-5 rounded-xl border border-emerald-900/70 bg-emerald-950/20 p-4"><Sparkles size={18} className="text-emerald-400" /><p className="mt-3 font-medium text-emerald-200">No se ejecuta un envío sin número de prueba.</p><p className="mt-1 text-xs text-emerald-300/70">Abre el Centro de Pruebas con esta conexión preseleccionada y ejecuta el Smoke Test existente.</p></div><div className="mt-6 flex justify-between"><button onClick={() => setPhase('verification')} className="text-sm text-zinc-400 hover:text-zinc-200">Volver</button><div className="flex gap-2"><button onClick={() => created && onOpenTests?.(created.name)} disabled={!created} className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-700 px-3 py-2 text-sm text-zinc-200 disabled:opacity-40"><FlaskConical size={14} />Abrir pruebas</button><button onClick={complete} className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white">Finalizar <Check size={14} /></button></div></div></section> : null}
      {phase === 'complete' ? <section className="text-center"><CheckCircle2 size={38} className="mx-auto text-emerald-400" /><h3 className="mt-4 text-xl font-semibold text-zinc-100">Conexión finalizada</h3><p className="mt-2 text-sm text-zinc-500">{created?.name || name} quedó lista en {duration(Date.now() - startedAt)}. El historial local conserva esta ejecución para futuras auditorías.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><button onClick={() => created && onOpenWorkspace?.(created.name)} className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white"><ExternalLink size={14} />Abrir Workspace</button><button onClick={() => created && onOpenTests?.(created.name)} className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-700 px-4 py-2.5 text-sm text-zinc-200"><FlaskConical size={14} />Smoke Test</button><button onClick={onClose} className="px-4 py-2.5 text-sm text-zinc-400 hover:text-zinc-200">Cerrar</button></div></section> : null}
      {phase === 'failed' ? <section><AlertTriangle size={30} className="text-red-400" /><h3 className="mt-4 text-xl font-semibold text-zinc-100">El onboarding necesita atención</h3><div className="mt-4 rounded-xl border border-red-900/70 bg-red-950/20 p-4"><p className="font-medium text-red-200">{error?.message}</p><p className="mt-2 text-sm text-red-100/80">Qué hacer: {error?.action}</p>{error?.technical ? <button onClick={() => setShowTechnical(value => !value)} className="mt-3 text-xs text-red-300 underline">{showTechnical ? 'Ocultar detalle técnico' : 'Ver detalle técnico'}</button> : null}{showTechnical && error?.technical ? <pre className="mt-2 overflow-auto rounded border border-red-900 bg-zinc-950 p-2 text-left text-[11px] text-zinc-400">{error.technical}</pre> : null}</div><div className="mt-6 flex justify-between"><button onClick={cancel} className="text-sm text-zinc-400 hover:text-zinc-200">Guardar y cerrar</button><button onClick={retry} className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white"><RefreshCw size={14} />Reintentar desde esta etapa</button></div></section> : null}
      {error && !['failed'].includes(phase) ? <div className="mt-5 rounded-lg border border-amber-900/70 bg-amber-950/20 p-3 text-sm text-amber-200"><p>{error.message}</p><p className="mt-1 text-xs">{error.action}</p></div> : null}
      <section className="mt-8 border-t border-zinc-800 pt-4"><div className="flex items-center gap-2 text-xs text-zinc-500"><ClipboardList size={13} />Historial local reciente</div><div className="mt-2 flex flex-wrap gap-2">{readHistory().slice(0, 3).map(item => <span key={item.id} className="rounded border border-zinc-800 bg-zinc-950/50 px-2 py-1 text-[11px] text-zinc-500">{item.name} · {item.result} · {new Date(item.startedAt).toLocaleDateString()}</span>)}{readHistory().length === 0 ? <span className="text-[11px] text-zinc-600">Aún no hay onboardings finalizados.</span> : null}</div></section>
    </div></main></div></div></div>
}
